### ISSUE TITLE
Rename Screenshots directory and its files

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/android-contacts-scifiui#4]
Rename `Screenshots` directory to `assets` and change file names inside that directory to numbered file names 
eg: 1.jpeg, 2.jpeg,.............

As these screenshots are used in `README.md` file, the new directory name needs to be updated for snapshots path in readme file.

**Comment by GnikDroy** [comment]
Actually, isn't it a bad idea to keep screenshots in your master branch? Since that will increase your repository size dramatically every time they are changed. It would be a better idea to make a separate branch named screenshots containing only the screenshots. You can then reference these images in the separate branch to your README. (Or you could host these images somewhere else)

**Comment by arshadkazmi42** [comment]
@GnikDroy Keeping it in different branch sounds good, I didn't thought about it.
Please go ahead and create a PR with this if you want to work on this

**Comment by nishant-nimbare** [comment]
can I do this?

**Comment by sankalpchauhan-me** [comment]
PR #18

**Comment by arshadkazmi42** [comment]
@nishant-nimbare thank you for working on this.
